version: '2'
services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    environment:
      ADMIN_PASSWORD : pw123
      JVM_ARGS : -Xmx2g
    ports:
    - 3030:3030
    volumes:
      - fuseki-data:/fuseki